# Site settings
title: Independent Stove Installations
email: your-email@domain.com
description: Hetas approved wood burner and multi fuel stove fitters, Bristol, UK. Stove, fireplace and chimney flue installation.
keywords: stove,wood burner,fitter,installer,engineer,installations,HETAS,Bristol,fireplace,multifuel stove,wood burning stove
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.independentstoveinstallations.co.uk" # the base hostname & protocol for your site
company-description: |
  [HETAS approved stove installers](http://www.hetas.co.uk/consumer), Bristol, UK.
telephone: |
  Telephone: Dylan - [07843 272 752](tel:07843 272 752) or  Nick - [07812 412 030](tel:07812 412 030)

copyright: |
  &copy; Independent Stove Installations. [HETAS approved stove installers](http://www.hetas.co.uk/consumer), Bristol, UK.
credits: |

# Build settings
markdown: kramdown
include:
  - .well-known
exclude:
  - unicorn.rb
  - README.md
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - legacy-gallery.csv
  - legacy-gallery-fullsize.csv
gems:
  - jekyll-sitemap
