# Site settings
offline: false
offline_message: Due to unforseen circumstances we're not booking new work for the time being.
title: Wood burner fitters and multi fuel stove installers, Bristol
company-name: Independent Stove Installations
email: your-email@domain.com
description: Hetas approved wood burner and multi fuel stove fitters, Bristol, Bath and Somerset. Stove, fireplace and chimney flue installation.
keywords: stove,wood burner,log burner,fitter,installer,engineer,installations,HETAS,Bristol,fireplace,multifuel stove,wood burning stove
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://independentstoveinstallations.co.uk" # the base hostname & protocol for your site
company-description: |
  [HETAS approved stove installers](http://www.hetas.co.uk/consumer), Bristol, UK.
telephone: |
  Telephone: Dylan - [07843 272 752](tel:07843 272 752)

copyright: |
  &copy; Independent Stove Installations. [HETAS approved stove installers](http://www.hetas.co.uk/consumer), Bristol, UK.
credits: |

# Build settings
markdown: kramdown
include:
  - .well-known
exclude:
  - unicorn.rb
  - README.md
  - Procfile
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - config.ru
  - vendor
  - app.json
  - legacy-gallery.csv
  - legacy-gallery-fullsize.csv
  - firebase.json
plugins:
  - jekyll-sitemap
sass:
  style: compressed
