source 'https://rubygems.org'

ruby '2.2.2'
gem 'bundler'
gem 'jekyll', '2.5.3'
gem 'rack-jekyll', :git => 'https://github.com/adaoraul/rack-jekyll.git', :require => 'rack/jekyll'
gem 'kramdown'
gem 'rake'
gem 'jekyll-sitemap'
gem 'unicorn'
