source 'https://rubygems.org'

ruby '2.7.2'
gem 'bundler'
gem 'jekyll', '4.2.0'
gem 'rack-jekyll', :git => 'https://github.com/adaoraul/rack-jekyll.git', :require => 'rack/jekyll'
gem 'kramdown'
gem 'rake'
gem 'jekyll-sitemap'
gem 'unicorn'
