source 'https://rubygems.org'

ruby '2.6.3'
gem 'bundler'
gem 'jekyll', '3.8.5'
gem 'rack-jekyll', :git => 'https://github.com/adaoraul/rack-jekyll.git', :require => 'rack/jekyll'
gem 'kramdown'
gem 'rake'
gem 'jekyll-sitemap'
gem 'unicorn'
